### ISSUE TITLE
Where is the variable df_status defined?

### ISSUE THREAD

**Issue by Robinaoko** [rupakdas18/SemEval-2017-Task-4-A-B-C-using-BERT#1]
Hi! 
I was running your code and found that df_status is not defined. 
What is df_status?

**Comment by rupakdas18** [comment]
@Robinaoko , In which program file did you get this issue? Can you please also upload a screenshot of the error?
As per what I know, df_status is to get a summary of a data frame. I have also uploaded the Google Co-Lab files here. You can also try them.

**Comment by Robinaoko** [comment]
In these three program files:
![{LSWL)1QLQBA~H(FM)9T9IA](https://user-images.githubusercontent.com/68173679/162949489-d4abc3b5-a182-436a-a300-0a4c26c7645a.png)

Here is the error:
![image](https://user-images.githubusercontent.com/68173679/162949771-efce448b-5f24-4fda-9270-0368be16e970.png)


Code:
![W@38AIO37SOQ%1@WX`5`B6Y](https://user-images.githubusercontent.com/68173679/162949863-3f4469bd-36cd-41dc-a1e6-43d96eba3a03.png)

**Comment by rupakdas18** [comment]
@Robinaoko , I have updated the files. Please let me know if it works now

**Comment by Robinaoko** [comment]
It works now. 
Thank you！
